name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Running a one-line script! It works!!

      - name: Run a multi-line script
        run: |
          echo Running a multi-line script! Line 1
          echo Line 2. It works!!
